name: drive_safe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  camera: ^0.10.6
  http: ^1.3.0
  html: ^0.15.5

  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  go_router: ^14.8.1

  image_picker: ^0.8.6
  image: ^4.1.3
  universal_html: ^2.0.8
  intl: ^0.17.0 # Add the intl package
  flutter_image_compress: ^2.4.0 # Updated version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  image_picker_for_web: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Thin.ttf
          weight: 100
        - asset: fonts/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: fonts/RobotoSlab-Light.ttf
          weight: 300
        - asset: fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: fonts/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: fonts/RobotoSlab-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
